### ISSUE TITLE
Packages are not available

### ISSUE THREAD

**Issue by vettom** [AdobeDocs/experience-manager-dispatcher.en#1]
Hi,
All links for downloading package is returnign 404

**Comment by jsamayoa-xumak** [comment]
It seem that links are broken for dispatcher version 4.3.1, but work if you change the link to 4.3.2

Example:

https://download.macromedia.com/dispatcher/download/dispatcher-apache2.4-linux-x86_64-4.3.1.tar.gz
https://download.macromedia.com/dispatcher/download/dispatcher-apache2.4-linux-x86_64-4.3.2.tar.gz

**Comment by raimanS** [comment]
The page has been updated with the latest information, see [1].
[1] - https://docs.adobe.com/content/help/en/experience-manager-dispatcher/using/getting-started/release-notes.html
