### ISSUE TITLE
Optional Directives/Parameters?

### ISSUE THREAD

**Issue by bstopp** [AdobeDocs/experience-manager-dispatcher.en#10]
Issue in help/using/dispatcher-configuration.md

Can the individual parameters for directives be marked as Optional, for those that are optional?

For example `headers` is a an optional parameter in the `/cache` section, but it is not indicated on the docs.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
See CQDOC-17795 for further details.
