### ISSUE TITLE
Auth Checker not referenced on property list

### ISSUE THREAD

**Issue by bstopp** [AdobeDocs/experience-manager-dispatcher.en#12]
Issue in help/using/dispatcher-configuration.md

The list of all available directives doesn't include the `auth_checker` parameter. Even if there is another page describing the use of  the directive, it should still be listed.

[Directive Reference List](https://docs.adobe.com/content/help/en/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html#defining-farms-farms)

[Detail page](https://docs.adobe.com/content/help/en/experience-manager-dispatcher/using/configuring/permissions-cache.html)

**Comment by raimanS** [comment]
Page updated (auth_checker added to the list).
