### ISSUE TITLE
enableTTL section errors

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/experience-manager-dispatcher.en#18]
I submitted PR #17 to fix a number of issues with the 'enableTTL' section of the document. These include:

1. enableTTL is part of the cache section of the file, but it was at the wrong heading level in the doc, making it misleading about where to include it in the dispatcher.any file
1. The XML sample is no longer needed, as it's not a new feature anymore and this is inconsistent with the other properties above
1. Typo in the note `avaiable` -> `available`
1. Note made it seem like enableTTL was only available in 4.1.11 but should clarify "or later"

Please merge, @raimanS

**Comment by raimanS** [comment]
The changes are live at [1]. Thanks.

[1] - https://docs.adobe.com/content/help/en/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html
