### ISSUE TITLE
Invalid Links on Configuring Dispatcher with multiple domains document.

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-dispatcher.en#19]
Issue in help/using/dispatcher-domains.md

When I click on (See AEM Rewrites Incoming URLs .) and/or on (See The Web Server Rewrites Incoming URLs .) under URL Mapping section, they don't redirect to the correct section on the page. The URL changes, however, it seems as if the divs with those ids don't exist.

[Logged By Support]

**Comment by raimanS** [comment]
Issue fixed. See https://docs.adobe.com/content/help/en/experience-manager-dispatcher/using/configuring/dispatcher-domains.html#url-mapping
