### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by cwammes** [AdobeDocs/experience-manager-dispatcher.en#2]
Issue in help/using/dispatcher-configuration.md

The link to Designing Patterns for glob Properties does not go anywhere.
https://docs.adobe.com/content/help/en/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html#main-pars-title-25

**Comment by raimanS** [comment]
Fixed the broken links. See [1].
[1] - https://docs.adobe.com/content/help/en/experience-manager-dispatcher/using/configuring/dispatcher-configuration.htm
