### ISSUE TITLE
Typo in the dispatcher configuration doc

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-dispatcher.en#20]
Issue in help/using/dispatcher-configuration.md

Under section [1]

'Resolved virtual host' value shows "www.mycompany.com/products/*;" instead of "www.mycompany.com/products/*"

{Logged By Support}

[1] https://docs.adobe.com/content/help/en/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html#example-virtual-host-resolution

**Comment by bohnertchris** [comment]
Thank you for reporting this, @jbrarAdobe. Would you mind a screenshot? A search of the page reveals no string containing "www.mycompany.com/products/;" or even "/;". Perhaps this is no longer an issue?

**Comment by raimanS** [comment]
Hello. The fix has been published on Friday. I left the issue open as a reminder to re-check the content. Thanks.
