### ISSUE TITLE
Bullet points not aligned properly

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-dispatcher.en#22]
Issue in help/using/dispatcher-configuration.md

Bullet points on the dispatcher configuration pages are all misaligned.

Check under Dispatcher Configuration Files section Or Defining Farms just to quote few examples

[Logged By Support]

**Comment by bohnertchris** [comment]
Thank you for reporting this, @jbrarAdobe. This is likely (and rather unfortunately) an issue specific to Firefox as I was unable to replicate any problem except on Firefox. Can you confirm that you were using Firefox and if you see the problem on any other browser?

**Comment by jbrarAdobe** [comment]
@bohnertchris  - Thanks for checking. I can confirm this issue is only observed on Firefox.

**Comment by bohnertchris** [comment]
Thanks for the confirmation, @jbrarAdobe! We have ticket SSECD-412 logged with the SCCM team to address this.
