### ISSUE TITLE
Broken Links in Check the Basic Configuration section

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-dispatcher.en#27]
Issue in help/using/dispatcher-troubleshooting.md

Broken Links in _https://docs.adobe.com/content/help/en/experience-manager-dispatcher/using/troubleshooting/dispatcher-troubleshooting.html#check-the-basic-configuration_:
* Confirm Basic Operation
* logging
* Check your configuration

![image](https://user-images.githubusercontent.com/59624839/81343822-ac0efb80-9083-11ea-8015-409e937ea694.png)

[Logged by AEM Support]

**Comment by raimanS** [comment]
The broken links have been fixed [1].
 [1] - https://experienceleague.adobe.com/docs/experience-manager-dispatcher/using/troubleshooting/dispatcher-troubleshooting.html
