### ISSUE TITLE
SELinux setup is incorrect

### ISSUE THREAD

**Issue by paul-bjorkstrand** [AdobeDocs/experience-manager-dispatcher.en#28]
The section on https://github.com/AdobeDocs/experience-manager-dispatcher.en/blob/master/help/using/dispatcher-install.md#apache-web-server---configure-selinux-properties-apache-web-server-configure-selinux-properties describing how to configure SELinux is not correct. The context that the documentation says to use, `httpd_sys_content_t`, is a **read-only** context, so the httpd process (thus the dispatcher module) cannot write into the directory. The correct context is either `httpd_sys_rw_content_t` or `httpd_cache_t`.

I tend to use the latter, because the dispatcher is logically, and technically a cache. The former is also a valid  answer, though, since the httpd process needs to be able to write out the cache files.

**Comment by bohnertchris** [comment]
Thank you for pointing this out @paul-bjorkstrand! We will investigate.

**Comment by bohnertchris** [comment]
CQDOC-16122
