### ISSUE TITLE
Is there any dispatcher version for Windows Apache?

### ISSUE THREAD

**Issue by irenebijo** [AdobeDocs/experience-manager-dispatcher.en#31]
Issue in ./help/using/release-notes.md

**Comment by anujkapo** [comment]
@irenebijo, the release notes mention the dispatcher version as 4.3.3 in the Release Information section. Is that what you are looking for? Can you provide more details?

**Comment by anujkapo** [comment]
@irenebijo, hope you have got the information that you were looking for. If the problem still persists, please log a new issue. Thanks!
