### ISSUE TITLE
Validate Flush agents on publish instances

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-dispatcher.en#33]
Issue in help/using/page-invalidate.md

Need to add another Step between 6-7 under the "Invalidating Dispatcher Cache from a Publishing Instance" as follows:

Login to the publish instance and validate the flush agent configuration. Also, make sure it's enabled.

**Comment by aheim0** [comment]
Thanks for highlighting this, we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-16751.
