### ISSUE TITLE
VanityUrlsComponent points to old decomissioned PackageShare rather than Adobe Content Distribution site.

### ISSUE THREAD

**Issue by somarc** [AdobeDocs/experience-manager-dispatcher.en#34]
Issue in help/using/dispatcher-configuration.md

![image](https://user-images.githubusercontent.com/8710267/95348572-2c809500-088c-11eb-8e85-0128b1a6acb4.png)

Should be linked to here : 
https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html?package=/content/software-distribution/en/details.html/content/dam/aem/public/adobe/packages/granite/vanityurls-components

And all reference to Package Share should be changed to Software Distribution (https://experience.adobe.com/#/downloads)

**Comment by bohnertchris** [comment]
Nice catch, @somarc. Thank you.

**Comment by bohnertchris** [comment]
CQDOC-16931
