### ISSUE TITLE
Invalid/broken href value for statfile anchor tag

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-dispatcher.en#36]
Issue in ./help/using/dispatcher-configuration.md

**statfile** anchor tag has Invalid/broken href value.
**Href Value**: /docs/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html?lang=en#main-pars-title-28
![image](https://user-images.githubusercontent.com/59624839/98865049-cf52a300-2438-11eb-82d8-43cf4047dd4d.png)

When I click on that link, it changes the url in the browser, but doesn't take me anywhere.
![image](https://user-images.githubusercontent.com/59624839/98865149-fd37e780-2438-11eb-9da0-17e6bcef87d7.png)

[Logged by AEM Support]

**Comment by anujkapo** [comment]
Thanks, @sukohli. We will fix it.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17104.

**Comment by bohnertchris** [comment]
Thanks for reporting this, @sukohli. This was fixed in commit 0313495.
