### ISSUE TITLE
ignoreUrlParams should be as per the best practice

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-manager-dispatcher.en#37]
Issue in ./help/using/dispatcher-configuration.md

https://experienceleague.adobe.com/docs/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html?lang=en#ignoring-url-parameters 

The documentation should follow the best practice to ignore all parameter by default and only ignore the parameters which are meaningful to publisher. The dispatcher optimization tool has a good example which can be used.

https://github.com/adobe/aem-dispatcher-optimizer-tool/blob/main/docs/Rules.md#dot---the-dispatcher-publish-farm-cache-should-have-its-ignoreurlparams-rules-configured-in-an-allow-list-manner

**Comment by anujkapo** [comment]
Thanks, @himanshu-pathak. We will take a look.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17556.

**Comment by raimanS** [comment]
See CQDOC-19661.
