### ISSUE TITLE
Incorrect response documented for invalidate.cache

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-dispatcher.en#38]
Issue in ./help/using/dispatcher-configuration.md

Testing Dispatcher Security section states a 404 response should be received for confirmation.  If all is correct the response is 403.  

$ curl -H "CQ-Handle: /content" -H "CQ-Path: /content" https://myauthor/dispatcher/invalidate.cache
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /dispatcher/invalidate.cache
on this server.</p>
</body></html>

[Logged by support]

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17730.
