### ISSUE TITLE
Conditional headers in the example documentation

### ISSUE THREAD

**Issue by javiruizgonzalez** [AdobeDocs/experience-manager-dispatcher.en#40]
Issue in help/using/dispatcher-configuration.md

In the example for /clientheaders section there are the following headers:
  "if-match"
  "if-none-match"
  "if-range"
  "if-unmodified-since"

They should be removed due to dispatcher should never issue conditional requests if the response is not already cached.

**Comment by anujkapo** [comment]
Thanks, @javiruizgonzalez. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC
