### ISSUE TITLE
Link redirecting to "Older versions of Adobe Experience Manager, CQ, and CRX" page

### ISSUE THREAD

**Issue by epsilon-jka** [AdobeDocs/experience-manager-dispatcher.en#41]
Issue in ./help/using/page-invalidate.md

Page: https://experienceleague.adobe.com/docs/experience-manager-dispatcher/using/configuring/page-invalidate.html?lang=en
 The below highlighted link is being redirected to the "Older versions of Adobe Experience Manager, CQ, and CRX" page.

![image](https://user-images.githubusercontent.com/62014822/126763129-4f0ba3c5-fda1-41d8-9ab9-8c7c5d944288.png)

**Comment by anujkapo** [comment]
Thanks, @epsilon-jka. We will fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
Fixed the reference link
