### ISSUE TITLE
 Link to   information on clickjacking please see the OWASP site not working 

### ISSUE THREAD

**Issue by sarojmi2** [AdobeDocs/experience-manager-dispatcher.en#43]
Issue in ./help/using/security-checklist.md
information on clickjacking please see the OWASP site.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
The reference link has been updated.
