### ISSUE TITLE
[Question] EULA Link for the Dispatcher Module

### ISSUE THREAD

**Issue by clstia** [AdobeDocs/experience-manager-dispatcher.en#44]
Would like to ask if there is a public link for the EULA of the dispatcher module for Apache.

**Comment by aheim0** [comment]
Thank you for raising this - we will investigate.

**Comment by raimanS** [comment]
When you download a product/package from the software distribution site [1], there is an EULA tab to the right.
[1] - https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html
