### ISSUE TITLE
Dispatcher CHANGES and README files are not updated in 4.3.4 downloads

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/experience-manager-dispatcher.en#45]
Issue in ./help/using/release-notes.md
The downloads included on this webpage have two outdated files within:
CHANGES
README
Neither were updated with 4.3.4 information. This needs to be fixed by whomever packaged and uploaded these.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC
