### ISSUE TITLE
IIS support for dispatcher

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-dispatcher.en#46]
Issue in ./help/using/dispatcher-configuration.md

Hello,

I am working with Dispatcher and Microsoft IIS - most of the configuration is quire similar and works the same as on Apache but I had some issues with invalidateHandler section on windows ([more details here](https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/aem-dispatcher-invalidate-hanlder-for-iis/m-p/443240#M126641))

Could you please extend the `invalidateHandler` section with some guides for Windows users? Is there any additional configuration required? 

Thanks,
Bartek

**Comment by anujkapo** [comment]
Thanks, @bartoszWesolowski. We will investigate.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bartoszWesolowski** [comment]
Hello @raimanS , I noticed that this task was closed - was documentation updated on that matter? Could you share a link?I do not see any changes around that topic under https://experienceleague.adobe.com/docs/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html?lang=en#configuring-time-based-cache-invalidation-enablettl
