### ISSUE TITLE
/enableTTL missing config values

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-dispatcher.en#47]
Issue in ./help/using/dispatcher-configuration.md

Hi, I noticed that there is no example values that should be passed to `/enableTTL` directive, so it's unclear whether it should be just `/enableTTL` or `/enableTTL "1"` or `/enableTTL "0"`

Thanks,
Bartek

**Comment by bohnertchris** [comment]
Thanks for pointing this out, @bartoszWesolowski. We will look into this.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC
