### ISSUE TITLE
TTL caching changes response header caching

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-dispatcher.en#48]
Issue in ./help/using/dispatcher-configuration.md

Hello,

I noticed an undocumented behaviour when dispatcher is used with TTL. All details documented here: https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/dispatcher-enable-ttl-removes-headers-from-response/m-p/446177#M127628

Could you please include that connection between enablettl and headers configuration in the documentation?

Cheers,
Bartek

**Comment by anujkapo** [comment]
Thanks, @bartoszWesolowski. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC
