### ISSUE TITLE
Labelling off

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-dispatcher.en#54]
Issue in ./help/using/dispatcher-domains.md

In the diagram for "Cache Invalidation" the steps are labeled as A, B, and C. But in the descriptions below, they are labeled 1, 2, and 3. It's unclear that A, B, and C are mapped to 1, 2, and 3. These should be consistent and clear that they are describing the steps in the diagram.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
List fixed.
