### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-dispatcher.en#55]
Issue in ./help/using/dispatcher-domains.md
In this section: Environment for the Provided Examples
The first figure labeled "repository", the word "content" is spelled wrong.(site b > conent nodes)

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC
