### ISSUE TITLE
confusion on dispatcher config sessionmanagment section

### ISSUE THREAD

**Issue by masumalli** [AdobeDocs/experience-manager-dispatcher.en#56]
Issue in ./help/using/dispatcher-configuration.md

Issue: Customers are getting confused on [1], basically use of sessionmanagement, customers are presuming it will cache after authentication.

Request:

Please add a note to the following section [1], that if the sessionmanagement is configured, the pages are not cached. And make it clear the purpose of sessionmanaagement is to check auth header and enforce authentication on secured pages. And the those secured pages are not cached. If the customer needs caching, please point them to auth checker [2].

[1] Enabling Secure Sessions - /sessionmanagement
[2] https://experienceleague.adobe.com/docs/experience-manager-dispatcher/using/configuring/permissions-cache.html?lang=en

**Comment by anujkapo** [comment]
Thanks, we will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC
