### ISSUE TITLE
small typo in dispatcher info

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-dispatcher.en#57]
Issue in ./help/using/page-invalidate.md

Deleting cached files ins this manner is appropriate for web sites that are not likely to receive simultaneous requests for the same page.

The word ins should be in.

**Comment by aheim0** [comment]
Thanks for highlighting this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
Typo fixed.
