### ISSUE TITLE
Typo in virtual host config

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-dispatcher.en#59]
Issue in ./help/using/dispatcher-ssl.md

In section `Configuring Dispatcher to Use SSL` a sample code contains two farms definition, one to handle secure connections (https) and one to handle http connections.

In the sample code both `virtualhosts` sections has the same configuration 

```
      /virtualhosts
      {
         # select this farm for all incoming HTTPS requestss
         "https://*"
      }
```

As far as I understand the `non-secure` farm should have value `http://*` instead of `https://*`

![image](https://user-images.githubusercontent.com/9348327/197345121-e12ef392-ee30-4bf4-9e76-6665fa4fe4a0.png)

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC
