### ISSUE TITLE
Ignoring URL Parameters - additional info

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-dispatcher.en#61]
Issue in ./help/using/dispatcher-configuration.md

In the `Ignoring URL Parameters` section it is not stated what is used to match the glob configuration. Is it the full request url? Or just the query parameters string? It would be great to clarify this in the documentation.

Thanks :)

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @bartoszWesolowski. We will review.
