### ISSUE TITLE
Extend enableTTL section

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-dispatcher.en#62]
Issue in ./help/using/dispatcher-configuration.md

In the section about `enableTTL` property there is an additional info :`Keep in mind that TTL-based caching is a superset of header caching and as such the /headers property should also be properly configured.`

It's not clear to me what does it mean - maybe an example or some additional explanation would help to make it straight forward.

Thanks,
Bartek

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
We revamped the enableTTL section and updated the note. Thanks.
