### ISSUE TITLE
Section Vanity URLs needs to be updated

### ISSUE THREAD

**Issue by janwalz** [AdobeDocs/experience-manager-dispatcher.en#65]
The section about the Vanity URLs references a package in Software distribution that should be installed. The link is dead and searching for the package returns no results.

Additionally, for AEMaaCS a manual installation of this package is not needed at all. The described configuration in /farms is enough to use this feature.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by janwalz** [comment]
It seems it was a glitch, the link is now also working for me.

**Comment by raimanS** [comment]
@janwalz Thanks for the feedback.
