### ISSUE TITLE
Bad example description in filter section - allow vs deny

### ISSUE THREAD

**Issue by lklement** [AdobeDocs/experience-manager-dispatcher.en#69]
Issue in ./help/using/dispatcher-configuration.md
Current Text reads:

Example Filter: Allow Access to the Workflow Console
The following example shows a filter used to **deny** external access to the Workflow console:
/filter {
    /0001  { /glob "*" /type "deny" }
    /0002  {  /type "allow"  /url "/libs/cq/workflow/content/console*"  }
}

I believe the '**deny**' in the description should be "allow"

**Comment by guillaumecarlino** [comment]
Thank you for opening this issue. We will investigate.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
Thank you for the suggestion. The page has been updated [1].

[1] - https://experienceleague.adobe.com/docs/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html#example-virtual-host-resolution
