### ISSUE TITLE
Apache version to be used on dispatchers of different AEM versions like AEM 6.1,  AEM 6.2, etc is not provided

### ISSUE THREAD

**Issue by subramanya** [AdobeDocs/experience-manager-dispatcher.en#7]
Hi,
Please provide the information about which version of Apache  is supported on dispatchers of AEM 6.1 , AEM 6.2 etc. 
This information is highly required as security teams are raising vulnerability alerts on older version of Apache , example apache 2.2.X. 
AEM dispatcher may stop working if we simply upgrade the apache version on dispatcher.
If a particular version of Apache is supported on some version of AEM, then we will inform client to go for upgrade of AEM version first and then upgrade of dispatcher so that latest version of Apache can be used for dispatcher.

Thanks

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
You can check the supported versions on the technical requirements page, for example [1]. For older docsets please go here [2] and download/install the relevant documentation version and search for the technical requirements page. For example, in 6.3 it is still under the "Deploying" section. Hope this helps. Thanks.

[1] - https://experienceleague.adobe.com/docs/experience-manager-64/deploying/introduction/technical-requirements.html#dispatcher-platforms-web-servers
[2] - https://experienceleague.adobe.com/docs/experience-manager-release-information/aem-release-updates/previous-updates/aem-previous-versions.html
