### ISSUE TITLE
Confused Sample code under Example Virtual Host Resolution

### ISSUE THREAD

**Issue by lklement** [AdobeDocs/experience-manager-dispatcher.en#70]
Issue in ./help/using/dispatcher-configuration.md
Under the heading "**Example Virtual Host Resolution**" the code sample seems to have a small reversal in it.

It currently reads:

/farms
  {
  ***/myProducts***
    {
    /virtualhosts
      {
      "www._mycompany_.com"
      }
    /renders
      {
      /hostname "server1.myCompany.com"
      /port "80"
      }
    }
  ***/myCompany***
    {
    /virtualhosts
      {
      "www.mycompany.com/_products/*"_
      }
    /renders
      {
      /hostname "server2.myCompany.com"
      /port "80"
      }
    }
  }

It seems to me that the property names for myCompany and myProducts are reversed, given the virtualhosts value inside each one.

Functionally, the example works because we don't specify the content of server1 and server2, but tje swap makes the example very unclear for the beginner.

**Comment by raimanS** [comment]
Thank you for the suggestion. The page has been updated [1].

[1] - https://experienceleague.adobe.com/docs/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html#example-virtual-host-resolution
