### ISSUE TITLE
Allow vs deny confusion in example description.

### ISSUE THREAD

**Issue by lklement** [AdobeDocs/experience-manager-dispatcher.en#72]
Issue+in+./help/using/dispatcher-configuration.md

Under the heading "Example Filter: Allow Access to the Workflow Console" the descriptive text says deny although the title and sample code state allow.

**Comment by guillaumecarlino** [comment]
Thank you for opening this issue. We will investigate.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
Thank you for the suggestion. The page has been updated [1].

[1] - https://experienceleague.adobe.com/docs/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html#defining-a-filter
