### ISSUE TITLE
selectors

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-dispatcher.en#73]
Issue in ./help/using/dispatcher-configuration.md
you need to define what selectors are and how to use them.

**Comment by aheim0** [comment]
We will review your request.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Immediately under the first instance of the term selector there is a note:
"For more information about what part of the request line each of these elements references, see the Sling URL Decomposition wiki page."
The link takes you to the Apache Sling resources, including an explanation of selectors. 

Thanks for raising this and hope it helps.

Closing issue.
