### ISSUE TITLE
DispatcherLogLevel description is incorrect

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-dispatcher.en#76]
Issue in ./help/using/dispatcher-install.md

"DispatcherLogLevel" description is incorrect. The values are 1-5, not 0-4. See 
"https://helpx.adobe.com/experience-manager/kb/dispatcher-log-level-changed-in-4-2-3.html"
 This was changed Dispatcher 4.2.3.

Thanks,
John

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
The document was double checked by an engineer and he confirmed that for versions 4.3.3 and later, the documentation was correct. That KB article is about version 4.2.3 and is irrelevant now.
