### ISSUE TITLE
There is a typo the module name, need to remove an errant underscore

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-dispatcher.en#77]
Issue in ./help/using/dispatcher-install.md

There is a typo in the module name "<IfModule disp \ _apache2.c>", the backslash needs to be removed.

This appears in more than one place in this document.

Thanks,
John

**Comment by johnb4** [comment]
It displays as "disp" followed by a backslash, followed by "_apache2.c" when there should not be any backslash and it should look like this "disp_apache2.c".

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC
