### ISSUE TITLE
Download links for Dispatcher 4.3.7 do not work

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/experience-manager-dispatcher.en#79]
Issue in ./help/using/release-notes.md

Download links do not work; they link back to the release notes page instead of pointing to a download location.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
I updated the two links at the top (Apache, IIS), they should now point to the appropriate download sections further down the page.
