### ISSUE TITLE
Links to previous versions not available

### ISSUE THREAD

**Issue by bstopp** [AdobeDocs/experience-manager-dispatcher.en#8]
The documentation only links to the most recent release of the Dispatcher module. There are times which previous versions are necessary.

**Comment by bstopp** [comment]
Any update on this request?

**Comment by twoznica90** [comment]
I have the same need, previous versions of the dispatcher need to be made available publicly.

**Comment by aheim0** [comment]
Thank you for raising this, we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-16789
